openapi: 3.0.3

info:
  version: 0.0.1
  title: Animals API
paths:

  /animals:
    parameters:
      - in: query
        name: filter
        required: true
        schema:
          $ref: "../data-dictionary/use-cases/get-animals.use-case.yml#/parameters/filter"
    get:
      tags:
        - animals
      summary: Retrieves animals.
      operationId: GetAnimals
      parameters:
        - in: query
          name: limit
          required: true
          schema:
            $ref: "../data-dictionary/use-cases/get-animals.use-case.yml#/parameters/limit"
        - in: query
          name: offset
          required: true
          schema:
            $ref: "../data-dictionary/use-cases/get-animals.use-case.yml#/parameters/offset"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/get_animals_response"

components:

  schemas:

    get_animals_response:
      allOf:
        - $ref: "../data-dictionary/base/offset-response.yml"
        - title: get animals response
          properties:
            animals:
              $ref: "../data-dictionary/use-cases/get-animals.use-case.yml#/response"