openapi: 3.0.3

info:
  version: 0.0.1
  title: Animals API
paths:

  /animals/{filter}:
    parameters:
      - in: path
        name: filter
        required: true
        schema:
          $ref: "./get-animals.use-case.yml#/parameters/filter"
    get:
      tags:
        - animals
      summary: Retrieves animals.
      operationId: GetAnimals
      parameters:
        - in: query
          name: limit
          required: false
          schema:
            $ref: "./get-animals.use-case.yml#/parameters/limit"
        - in: query
          name: offset
          required: false
          schema:
            $ref: "./get-animals.use-case.yml#/parameters/offset"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "./get-animals.use-case.yml#/response"